### PR TITLE
Fixing responsive designs

### PR DESCRIPTION
**Pull request by jamm59**
1. Home Page
image

**do not merge yet. Not finished**

### CODE REVIEW

**Comment by jamm59** [comment]
2. Blog Page
image
Functionality not complete yet. Users would be read more on each blog. will do that on another branch
**do not push to main yet**

**Comment by jamm59** [comment]
3. User Page

- image

- image

- image


Do not make a pull request yet. Not done

**Comment by jamm59** [comment]
I've done a lot of refactoring with the code

**Comment by harrykeeran12** [comment]
Could you add some comments?

**Review by CodingEloise — APPROVED** [review]

**Comment by jamm59** [comment]
> Could you add some comments? @jamm59

of course

**Comment by harrykeeran12** [comment]
How long would it take do you think to implement a working version of the accessibility feature? 
Just because we could probably add it to a roadmap of features.

**Comment by jamm59** [comment]
> How long would it take do you think to implement a working version of the accessibility feature? Just because we could probably add it to a roadmap of features.

image
I could get, descriptive links, fontsize, bold, themes, highcontrast mode and alt for images to work by the end of next week

**Comment by jamm59** [comment]
More ui changes 

1. image
2. image
3. image
4. image
**For the admin page**
5. image

**Comment by jamm59** [comment]
image
changed the cards ui on the home page

**Comment by harrykeeran12** [comment]
The new card UI looks really good! though maybe have the prep time + cook time be displayed, but keep the type of food as a tag??

**Comment by jamm59** [comment]
okay will do that

**Review by harrykeeran12 — APPROVED** [review]
I think everything looks okay, but make sure the documentation makes sense for our project, because some stuff just doesnt apply.

**Comment by jamm59** [comment]
changed the design on the cards
image

**Pull request merged**
