### PR TITLE
admin page

### PR DESCRIPTION
**Pull request by harrykeeran12**

### CODE REVIEW

**Comment by jamm59** [comment]
image
Fixed the overflow issues and the new admin design

image
tried to make the font and color more consistent font and color more consistent

**Review by jamm59 — APPROVED** [review]

**Comment by harrykeeran12** [comment]
Because we aren't storing the goals, it doesnt really make sense for the goals to be there, might be better to replace those with the user's allergies and dietary restrictions

**Comment by jamm59** [comment]
> Because we aren't storing the goals, it doesnt really make sense for the goals to be there, might be better to replace those with the user's allergies and dietary restrictions

but we are not really storing anything else at the moment. it's all stored on the localstorage, creating an illusion. Not sure what you mean, but I will take it out.

**Comment by jamm59** [comment]
image


taken out personal goals

**Comment by harrykeeran12** [comment]
It would be easier to connect it up to the API later(if we have time) if its a lot more consistent
also for the local storage stuff did you store it by userID? because otherwise when you switch user it goes crazy

**Review by zbbbbbbbc — APPROVED** [review]

**Pull request merged**
