### PR TITLE
Changed the ui for DailyIntake. Added a food and water log component

### PR DESCRIPTION
**Pull request by jamm59**
image

image

### CODE REVIEW

**Comment by jamm59** [comment]
https://github.com/nutrition-monitoring-system/nhms/assets/52214276/22e132da-5883-4256-9c99-8ac11e94ba90

Got the AI feature to work for the nutritional information

**Comment by jamm59** [comment]
image

**Review by harrykeeran12 — APPROVED** [review]
All looks good I think.

**Comment by harrykeeran12** [comment]
> image
> At some point in the future we might need to pay for this service if we want to keep using it

Maybe we should disable it for now and add a tooltip or something saying that it's a premium feature?

**Comment by harrykeeran12** [comment]
@jamm59 Could you make sure that the boxes are all the same size? and that they look neat?

**Comment by harrykeeran12** [comment]
Still not ready to merge right? @jamm59

**Review by nann7 — APPROVED** [review]

**Pull request merged**
